//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Export_Permission
    {
        public int ID { get; set; }
        public Nullable<int> Quentity { get; set; }
        public System.DateTime Date { get; set; }
        public int Store_id { get; set; }
        public int Prod_Code { get; set; }
        public Nullable<int> Cust_id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
    }
}
